### ISSUE TITLE
no button rendered in admin dashboard

### ISSUE THREAD

**Issue by bmbaron** [lautr/strapi-plugin-duplicate-button#12]
Hi, is this still working for Strapi with version v4.10.X and Node version > 16?

I've followed the instructions and can see   
    _"strapi-plugin-duplicate-button": "^1.1.7"_
in my package.json

I've also added _'duplicate-button': true_ to config/plugins.js

Duplicate Button is also now listed in my plugin on the localhost:1337 Dashboard.

However, I don't see the button displaying in the edit view for any of my collection types. What do you recommend?

Thanks for any insight!

**Comment by dragGH102** [comment]
Same issue - node v18

**Comment by lautr** [comment]
Hi @bmbaron and @dragGH102,

Thank you for raising this issue and providing detailed information about it. 

I've just conducted a test with a fresh Strapi (Strapi v 4.10.5 & Node 18.16.0) installation and can confirm that the duplicate button is functioning as expected. Please refer to this link for reference: https://github.com/lautr/strapi-duplicate-installed.

To resolve the issue you're encountering, you might want to try removing the plugin configuration first. This is because the 'duplicate-button': true setting in config/plugins.js is typically not required for the plugin to function correctly in most cases.

However, if the problem persists even after you've removed the plugin configuration, please feel free to provide me with a reproduceable example. I'll be more than happy to delve deeper into this and assist you further.

Best regards

**Comment by bmbaron** [comment]
Hi @lautr, thanks for helping with this.

> To resolve the issue you're encountering, you might want to try removing the plugin configuration first. This is because the 'duplicate-button': true setting in config/plugins.js is typically not required for the plugin to function correctly in most cases.

This was indeed my issue, and after removing that setting, the "duplicate" button is visible and functioning well! 

Cheers,
Ben
